name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t dravula/hello-world-nodejs-ecs:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push dravula/hello-world-nodejs-ecs:${{ github.sha }}

    - name: Deploy to ECS
      run: |
        cd terraform
        terraform init
        terraform apply --auto-approve
